version: "3.0"
services:
  fleet_manager:
    image: fleet_manager:dev
    container_name: fleet_manager
    restart: always
    build: .
    environment:
      PGHOST: localhost
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: ati_fleet
      PGTZ: Asia/Kolkata
      TZ: Asia/Kolkata
      FM_DATABASE_URI: postgresql://postgres:postgres@localhost
      FM_MONGO_DATABASE_URI: mongodb://ati:atiMongo@localhost:27017
    expose:
     - 8001
    volumes:
      - .:/app/static
    depends_on:
      - db
      - mongo
    network_mode: host
  
  plugins:
    image: plugin:dev
    container_name: fm_plugins
    restart: always
    build: .
    environment:
      PGTZ: Asia/Kolkata
      TZ: Asia/Kolkata
      PLUGIN_DATABASE_URI: postgresql://postgres:postgres@localhost
      PLUGIN_MONGO_DATABASE_URI: mongodb://ati:atiMongo@localhost:27017
    expose:
     - 8002
    volumes:
      - .:/app/static
    depends_on:
      - db
      - mongo
    network_mode: host
  
  db:
    image: postgres:14.0
    container_name: fleet_db
    restart: always
    environment:
      - TZ=Asia/Kolkata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ati_fleet
    expose:
      - 5432
    volumes:
      - ./psql/psql_backup:/var/lib/postgresql/data:rw
    network_mode: host
 
  grafana:
    image: fm_grafana:9.5.2
    container_name: fm_grafana
    restart: always
    user: "root:root"
    expose:
      - 3000
    network_mode: host

  mongo:
    image: mongo
    container_name: fm_mongo
    restart: always
    expose:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ati
      MONGO_INITDB_ROOT_PASSWORD: atiMongo
    volumes:
     - ./mongo:/data/db:rw
    network_mode: host

  mongo-express:
    image: mongo-express
    container_name: fm_mongo_express
    restart: always
    expose:
      - 8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ati
      ME_CONFIG_MONGODB_ADMINPASSWORD: atiMongo
      ME_CONFIG_MONGODB_URL: mongodb://ati:atiMongo@localhost:27017
      ME_CONFIG_SITE_BASEURL: "/config_editor"
      ME_CONFIG_BASICAUTH_USERNAME: "ati_support"
      ME_CONFIG_BASICAUTH_PASSWORD: "ati112"
    depends_on:
      - mongo
    network_mode: host

  reverseproxy:
    image: fm_nginx:1.23.3
    container_name: reverseproxy
    hostname: fm_rev_proxy
    restart: always
    expose:
      - 443
    volumes:
      - ./certs:/certs
    depends_on:
      - fleet_manager
      - plugins
      - grafana
      - registry
      - mongo-express
    network_mode: host

  registry:
    restart: always
    image: registry:2
    container_name: fm_docker_registry
    expose:
      - 5000
    network_mode: host
