{
 "title": "FleetAnalytics",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   { "name": "fleetvar", "label": "Fleet_Selector ", "query": "master_fleet_map_superSet" }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "description": "Total trips run on the current date",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\nSELECT\n  COUNT(DISTINCT id)\nFROM\n  trips\nWHERE\nstart_time >= CAST($__timeFrom() AS timestamp with time zone)  AND end_time <= CAST($__timeTo() AS timestamp with time zone) AND\n  fleet_name = '$fleetvar' AND status='succeeded';\n"
    }
   ]
  },
  {
   "title": "Tug-Wise Distance",
   "type": "bargauge",
   "description": "Distance per sherpa (KM)",
   "gridPos": { "h": 8, "w": 10, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "rawSql": "\nSELECT\n  SUBSTRING(sherpa_name, 1, 6) AS Sherpa,\n  ROUND(SUM((SELECT SUM(s) FROM UNNEST(etas_at_start) s))) AS Distance\nFROM\n  trips\nWHERE\n  fleet_name = '$fleetvar'\n  AND sherpa_name IS NOT NULL\n  AND start_time >= CAST($__timeFrom() AS timestamp with time zone) AND end_time <= CAST($__timeTo() AS timestamp with time zone)\nGROUP BY\n  sherpa_name;"
    }
   ]
  },
  {
   "title": "Tug-Wise Trips",
   "type": "bargauge",
   "description": "Trips per sherpa",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "rawSql": "\nSELECT\n  SUBSTRING(sherpa_name, 1, 6) AS sherpa_substring,\n  COUNT(*) AS trip_count\nFROM\n  trips\nWHERE\n  start_time >= CAST($__timeFrom() AS timestamp with time zone)\n  AND end_time <= CAST($__timeTo() AS timestamp with time zone)\n  AND end_time IS NOT NULL\n  AND fleet_name = '$fleetvar'\n  AND status = 'succeeded'\nGROUP BY\n  sherpa_name;\n"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Total distance run on the current date",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(subquery.distance) AS Distance,\n  subquery.start_date AS Date\nFROM\n  (\n    SELECT\n      start_time::DATE AS start_date,\n      (SELECT SUM(s) FROM UNNEST(etas_at_start) s) AS distance\n    FROM\n      trips\n    WHERE\n      start_time >= CAST($__timeFrom() AS timestamp with time zone) AND end_time <= CAST($__timeTo() AS timestamp with time zone) AND\n      fleet_name = '$fleetvar'\n  ) AS subquery\nGROUP BY\n  subquery.start_date;\n"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "bargauge",
   "description": "Robot in fleetmode with ongoing trips / total hours in fleetmode\nThis statistic depends on how the client uses the bot.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "\n\nSELECT\n  SUBSTRING(sherpa_name, 1, 6) AS Sherpa,\n  ROUND(SUM(EXTRACT(EPOCH FROM (end_time - start_time)))/((CASE WHEN $__timeFrom()::DATE = CURRENT_DATE THEN extract(epoch from current_timestamp::time) ELSE 86400 END/100)*COUNT(DISTINCT(start_time::DATE)))) AS Utilization\nFROM\n  trips\nWHERE\n  status = 'succeeded'\n  AND sherpa_name IS NOT NULL\n  AND start_time IS NOT NULL\n  AND end_time IS NOT NULL\n  AND DATE_TRUNC('day', start_time) = DATE_TRUNC('day', end_time)\n  AND start_time >= CAST($__timeFrom() AS timestamp with time zone) AND end_time <= CAST($__timeTo() AS timestamp with time zone)\n  AND fleet_name = '$fleetvar'\nGROUP BY\n  sherpa_name;"
    }
   ]
  },
  {
   "title": "Average takt time",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "WITH joined_table AS (\n  SELECT\n  substring(t.sherpa_name,1,6) as Sherpa, t.route as Route, t.start_time as start_time, t.end_time as end_time, a.actual_trip_time as Trip_Time, a.time_elapsed_obstacle_stoppages as Obstacle_Time,\n  a.time_elapsed_visa_stoppages as Visa_Time, a.time_elapsed_other_stoppages as Other_Time, t.fleet_name\n  FROM\n    trips AS t\n  INNER JOIN\n    trip_analytics AS a ON t.id = a.trip_id\n  WHERE\n    t.fleet_name = '$fleetvar' AND t.start_time >= CAST($__timeFrom() AS timestamp with time zone) AND t.end_time <= CAST($__timeTo() AS timestamp with time zone)\n)\n\n\nSELECT\n  Sherpa,\n  Route,\n  AVG(EXTRACT(EPOCH FROM (end_time - start_time))) AS Trip_time\n\nFROM\n  (\n    SELECT\n      Sherpa,\n      Route,\n      start_time,\n      end_time,\n      ROW_NUMBER() OVER (PARTITION BY Sherpa ORDER BY COUNT(*) DESC) AS route_rank,\n      fleet_name\n    FROM\n      joined_table\n    GROUP BY\n      Sherpa,\n      Route,\n      start_time,\n      end_time,\n      fleet_name\n  ) ranked_data\nWHERE\n  route_rank = 1 AND fleet_name = '$fleetvar' AND\n  start_time >= CAST($__timeFrom() AS timestamp with time zone) AND end_time <= CAST($__timeTo() AS timestamp with time zone)\nGROUP BY\n  Sherpa,\n  Route;"
    }
   ]
  },
  {
   "title": "Average Obstacle Time",
   "type": "barchart",
   "description": "Average Obstacle Time for each tug on its most used route",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "WITH joined_table AS (\n  SELECT\n    substring(t.sherpa_name, 1, 6) as Sherpa, t.route as Route, t.start_time as start_time, t.end_time as end_time, t.fleet_name,\n    a.actual_trip_time as Trip_Time, a.time_elapsed_obstacle_stoppages as Obstacle_Time,\n    a.time_elapsed_visa_stoppages as Visa_Time, a.time_elapsed_other_stoppages as Other_Time\n  FROM\n    trips AS t\n  INNER JOIN\n    trip_analytics AS a ON t.id = a.trip_id\n  WHERE\n    t.fleet_name = '$fleetvar' AND t.start_time >= CAST($__timeFrom() AS timestamp with time zone) AND t.end_time <= CAST($__timeTo() AS timestamp with time zone)\n)\nSELECT\n  Sherpa,\n  Route,\n  AVG(Obstacle_Time) AS Total_Obstacle_Time\nFROM\n  (\n    SELECT\n      Sherpa,\n      Route,\n      start_time,\n      end_time,\n      Obstacle_Time,\n      fleet_name,\n      ROW_NUMBER() OVER (PARTITION BY Sherpa ORDER BY route_count DESC) AS route_rank\n    FROM\n      (\n        SELECT\n          Sherpa,\n          Route,\n          start_time,\n          end_time,\n          Obstacle_Time,\n          fleet_name,\n          COUNT(*) AS route_count\n        FROM\n          joined_table\n        GROUP BY\n          Sherpa,\n          Route,\n          start_time,\n          end_time,\n          Obstacle_Time,\n          fleet_name\n      ) counted_data\n  ) ranked_data\nWHERE\n  route_rank = 1 AND fleet_name = '$fleetvar' AND \n  start_time >= CAST($__timeFrom() AS timestamp with time zone) AND end_time <= CAST($__timeTo() AS timestamp with time zone)\nGROUP BY\n  Sherpa,\n  Route;\n"
    }
   ]
  },
  {
   "title": "Average Dispatch wait time",
   "type": "barchart",
   "description": "Average Time for each tug waits for dispatch button press at its most used route",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "WITH joined_table AS (\n  SELECT\n  substring(t.sherpa_name,1,6) as Sherpa, t.route as Route, t.start_time as start_time, t.end_time as end_time, t.trip_metadata as trip_metadata, t.fleet_name\n  FROM\n    trips AS t\n  INNER JOIN\n    trip_analytics AS a ON t.id = a.trip_id\n  WHERE\n    t.fleet_name = '$fleetvar' AND t.start_time >= CAST($__timeFrom() AS timestamp with time zone) AND t.end_time <= CAST($__timeTo() AS timestamp with time zone)\n)\n\nSELECT\n  Sherpa,\n  Route,\n  COALESCE(CAST(trip_metadata->>'total_dispatch_wait_time' as numeric),0) AS total_dispatch_time\n\nFROM\n  (\n    SELECT\n      Sherpa,\n      Route,\n      start_time,\n      end_time,\n      ROW_NUMBER() OVER (PARTITION BY Sherpa ORDER BY COUNT(*) DESC) AS route_rank,\n      fleet_name,\n      trip_metadata\n    FROM\n      joined_table\n    GROUP BY\n      Sherpa,\n      Route,\n      start_time,\n      end_time,\n      fleet_name,\n      trip_metadata\n  ) ranked_data\nWHERE\n  route_rank = 1 and fleet_name = '$fleetvar' AND \n  start_time >= CAST($__timeFrom() AS timestamp with time zone) AND end_time <= CAST($__timeTo() AS timestamp with time zone)\nGROUP BY\n  Sherpa,\n  Route,\n  trip_metadata;\n\n\n\n"
    }
   ]
  }
 ]
}