{
 "title": "FleetAnalytics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "fleetvar", "label": "Fleet_Selector " },
   { "name": "tz", "label": "Time Selector" }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "description": "Total trips run on the current date",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(DISTINCT id)\nFROM\n  trips\nWHERE\n  start_time >= CAST($__timeFrom() AS timestamp) AT TIME ZONE 'UTC' AT TIME ZONE '$tz'\n  AND end_time <= CAST($__timeTo() AS timestamp) AT TIME ZONE 'UTC' AT TIME ZONE '$tz'\n  AND fleet_name = '$fleetvar'\n  AND status = 'succeeded';"
    }
   ]
  },
  {
   "title": "Tug-Wise Distance",
   "type": "bargauge",
   "description": "Distance per sherpa (KM)",
   "gridPos": { "h": 10, "w": 10, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "km" } },
   "targets": [
    {
     "rawSql": "SELECT\n  CASE\n    WHEN SPLIT_PART(sherpa_name, '-', 3) IS NOT NULL THEN SPLIT_PART(sherpa_name, '-', 1) || '-' || SPLIT_PART(sherpa_name, '-', 2)\n    ELSE sherpa_name\n  END AS sherpa_name,\n  ROUND(\n    SUM(\n      (\n        SELECT\n          SUM(s)\n        FROM\n          UNNEST(route_lengths) s\n      )\n    )\n  ) / 1000 AS Distance\nFROM\n  trips\nWHERE\n  fleet_name = '$fleetvar'\n  AND status = 'succeeded'\n  AND sherpa_name IS NOT NULL\n  AND start_time >= CAST($__timeFrom() AS timestamp) AT TIME ZONE 'UTC' AT TIME ZONE '$tz'\n  AND end_time <= CAST($__timeTo() AS timestamp) AT TIME ZONE 'UTC' AT TIME ZONE '$tz'\nGROUP BY\n  sherpa_name;"
    }
   ]
  },
  {
   "title": "Tug-Wise Trips",
   "type": "bargauge",
   "description": "Trips per sherpa",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  CASE\n    WHEN SPLIT_PART(sherpa_name, '-', 3) IS NOT NULL THEN\n      SPLIT_PART(sherpa_name, '-', 1) || '-' || SPLIT_PART(sherpa_name, '-', 2)\n    ELSE\n      sherpa_name\n  END AS sherpa_name,\n  COUNT(*) AS trip_count\nFROM\n  trips\nWHERE\n  start_time >= CAST($__timeFrom() AS timestamp) AT TIME ZONE 'UTC' AT TIME ZONE '$tz'\n  AND end_time <= CAST($__timeTo() AS timestamp) AT TIME ZONE 'UTC' AT TIME ZONE '$tz'\n  AND end_time IS NOT NULL\n  AND fleet_name = '$fleetvar'\n  AND status = 'succeeded'\nGROUP BY\n  sherpa_name;\n"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Total distance run on the current date",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "km" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(subquery.distance) / 1000 AS Distance,\n  subquery.start_date AS Date\nFROM\n  (\n    SELECT\n      start_time :: DATE AS start_date,\n      (\n        SELECT\n          SUM(s)\n        FROM\n          UNNEST(route_lengths) s\n      ) AS distance\n    FROM\n      trips\n    WHERE\n      start_time >= CAST($__timeFrom() AS timestamp) AT TIME ZONE 'UTC' AT TIME ZONE '$tz'\n      AND end_time <= CAST($__timeTo() AS timestamp) AT TIME ZONE 'UTC' AT TIME ZONE '$tz'\n      AND fleet_name = '$fleetvar'\n      AND status = 'succeeded'\n  ) AS subquery\nGROUP BY\n  subquery.start_date;"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "bargauge",
   "description": "Robot in fleetmode with ongoing trips / total hours in fleetmode\nThis statistic depends on how the client uses the bot.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "WITH Numerator AS (\n  SELECT\n    sherpa_name,\n    SUM(\n      EXTRACT(\n        EPOCH\n        FROM\n          (end_time - start_time)\n      )\n    ) as trip_time\n  FROM\n    trips\n  WHERE\n    start_time >= CAST($__timeFrom() AS timestamp) AT TIME ZONE 'UTC' AT TIME ZONE '$tz'\n    AND end_time <= CAST($__timeTo() AS timestamp) AT TIME ZONE 'UTC' AT TIME ZONE '$tz'\n    AND fleet_name = '$fleetvar'\n    AND status = 'succeeded'\n    AND sherpa_name is NOT NULL\n  GROUP BY\n    sherpa_name\n),\nDenominator AS (\n  SELECT\n    SUM(\n      EXTRACT(\n        EPOCH\n        FROM\n          (MAX_end_time - MIN_start_time)\n      )\n    ) AS total_denominator\n  FROM\n    (\n      SELECT\n        MAX(end_time) AS MAX_end_time,\n        MIN(start_time) AS MIN_start_time\n      FROM\n        trips\n      WHERE\n        start_time >= CAST($__timeFrom() AS timestamp) AT TIME ZONE 'UTC' AT TIME ZONE '$tz'\n        AND end_time <= CAST($__timeTo() AS timestamp) AT TIME ZONE 'UTC' AT TIME ZONE '$tz'\n        AND fleet_name = '$fleetvar'\n        AND status = 'succeeded'\n        AND sherpa_name is NOT NULL\n      group by\n        end_time :: date\n    ) AS subquery\n)\nSELECT\n  CASE\n    WHEN SPLIT_PART(n.sherpa_name, '-', 3) IS NOT NULL THEN SPLIT_PART(n.sherpa_name, '-', 1) || '-' || SPLIT_PART(n.sherpa_name, '-', 2)\n    ELSE n.sherpa_name\n  END AS Sherpa,\n  ROUND(n.trip_time / d.total_denominator * 100) AS Utilization\nFROM\n  Numerator n\n  CROSS JOIN Denominator d\nWHERE\n  n.trip_time > 0;"
    }
   ]
  },
  {
   "title": "Average takt time",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "select\n  Sherpa,\n  route,\n  Trip_time as \"Average Takt time\"\nfrom\n  (\n    SELECT\n    CASE\n      WHEN SPLIT_PART(t.sherpa_name, '-', 3) IS NOT NULL THEN SPLIT_PART(t.sherpa_name, '-', 1) || '-' || SPLIT_PART(t.sherpa_name, '-', 2)\n      ELSE t.sherpa_name\n    END AS Sherpa,\n      t.route,\n      AVG(\n    EXTRACT(\n      EPOCH\n      FROM\n        (t.end_time - t.start_time)\n    )\n  ) AS Trip_time,\n      ROW_NUMBER() over(\n        partition by t.sherpa_name\n        order by\n          count(*) DESC\n      ) as route_rank\n    from\n      trips t\n      join trip_analytics a on a.trip_id = t.id\n    where\n      t.start_time >= CAST($__timeFrom() AS timestamp) AT TIME ZONE 'UTC' AT TIME ZONE '$tz'\n      and t.end_time <= CAST($__timeTo() AS timestamp) AT TIME ZONE 'UTC' AT TIME ZONE '$tz'\n      and fleet_name = '$fleetvar'\n      and status = 'succeeded'\n    group by\n      t.sherpa_name,\n      t.route\n  ) as d\nwhere\n  route_rank = 1;"
    }
   ]
  },
  {
   "title": "Average Obstacle Time",
   "type": "barchart",
   "description": "Average Obstacle Time for each tug on its most used route",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "select\n  sherpa_name,\n  route,\n  avg_obstacle_time as \"Average Obstacle time\"\nfrom\n  (\n    select\n      t.sherpa_name,\n      t.route,\n      AVG(a.time_elapsed_obstacle_stoppages) as avg_obstacle_time,\n      ROW_NUMBER() over(\n        partition by t.sherpa_name\n        order by\n          count(*) DESC\n      ) as route_rank\n    from\n      trips t\n      join trip_analytics a on a.trip_id = t.id\n    where\n      t.start_time >= CAST($__timeFrom() AS timestamp) AT TIME ZONE 'UTC' AT TIME ZONE '$tz'\n      and t.end_time <= CAST($__timeTo() AS timestamp) AT TIME ZONE 'UTC' AT TIME ZONE '$tz'\n      and fleet_name = '$fleetvar'\n      and status = 'succeeded'\n    group by\n      t.sherpa_name,\n      t.route\n  ) as d\nwhere\n  route_rank = 1;"
    }
   ]
  },
  {
   "title": "Average Dispatch wait time",
   "type": "barchart",
   "description": "Average Time for each tug waits for dispatch button press at its most used route",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "select\n  Sherpa,\n  route,\n  dispatch_time as \"Average Dispatch Wait time\"\nfrom\n  (\n    SELECT\n    CASE\n      WHEN SPLIT_PART(t.sherpa_name, '-', 3) IS NOT NULL THEN SPLIT_PART(t.sherpa_name, '-', 1) || '-' || SPLIT_PART(t.sherpa_name, '-', 2)\n      ELSE t.sherpa_name\n    END AS Sherpa,\n      t.route,\n      Avg(COALESCE(\n    CAST(\n      trip_metadata ->> 'total_dispatch_wait_time' as numeric\n    ),\n    0\n  )) AS dispatch_time,\n      ROW_NUMBER() over(\n        partition by t.sherpa_name\n        order by\n          count(*) DESC\n      ) as route_rank\n    from\n      trips t\n      join trip_analytics a on a.trip_id = t.id\n    where\n      t.start_time >= CAST($__timeFrom() AS timestamp) AT TIME ZONE 'UTC' AT TIME ZONE '$tz'\n      and t.end_time <= CAST($__timeTo() AS timestamp) AT TIME ZONE 'UTC' AT TIME ZONE '$tz'\n      and fleet_name = '$fleetvar'\n      and status = 'succeeded'\n    group by\n      t.sherpa_name,\n      t.route\n  ) as d\nwhere\n  route_rank = 1;"
    }
   ]
  }
 ]
}