#!/usr/bin/env python3
"""Generate pyreverse diagrams showing fleet_manager's usage of mule APIs.

This script:
1. Identifies fleet_manager files that import mule
2. Runs pyreverse on those fleet_manager files to visualize the structure
3. Highlights fleet_manager's dependencies on mule in SVG format
"""
import ast
import subprocess
import shutil
import sys
from pathlib import Path
from collections import defaultdict


def find_fm_files_using_mule(fm_root: Path):
    """Find all fleet_manager files that import mule."""
    files_with_mule = []
    
    for py_file in sorted(fm_root.rglob('*.py')):
        # Skip mule submodule itself
        if 'mule' in py_file.parts:
            continue
        
        try:
            src = py_file.read_text(encoding='utf-8', errors='ignore')
            tree = ast.parse(src, filename=str(py_file))
        except SyntaxError:
            continue
        except Exception:
            continue
        
        # Check for mule/ati imports
        has_mule_import = False
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    if alias.name.startswith(('mule', 'ati')):
                        has_mule_import = True
                        break
            elif isinstance(node, ast.ImportFrom):
                if node.module and node.module.startswith(('mule', 'ati')):
                    has_mule_import = True
                    break
        
        if has_mule_import:
            files_with_mule.append(str(py_file))
    
    return files_with_mule


def main():
    repo_root = Path(sys.argv[1]) if len(sys.argv) > 1 else Path('.')
    fm_root = repo_root  # Analyze from repo root, pyreverse will filter by import
    out_dir = repo_root / 'docs' / 'dep_graphs'
    out_format = (sys.argv[2] if len(sys.argv) > 2 else 'svg').lower()
    
    out_dir.mkdir(parents=True, exist_ok=True)
    
    # Find fleet_manager files that use mule
    fm_files = find_fm_files_using_mule(fm_root)
    
    if not fm_files:
        print("No fleet_manager files importing mule found.")
        sys.exit(1)
    
    print(f"Found {len(fm_files)} fleet_manager files using mule:")
    for f in fm_files[:5]:
        print(f"  - {f}")
    if len(fm_files) > 5:
        print(f"  ... and {len(fm_files) - 5} more")
    
    pyreverse = shutil.which('pyreverse')
    if not pyreverse:
        print('pyreverse not found on PATH')
        sys.exit(2)
    
    # Run pyreverse on fleet_manager files that use mule
    cmd = [pyreverse, '-o', out_format, '-p', 'fleet_manager_on_mule'] + fm_files
    print(f'\nRunning pyreverse on {len(fm_files)} files...')
    try:
        subprocess.run(cmd, check=True)
    except subprocess.CalledProcessError as e:
        print('pyreverse failed:', e)
        sys.exit(3)
    
    # Move generated files to docs/dep_graphs
    cwd = Path.cwd()
    generated = list(cwd.glob(f'classes_fleet_manager_on_mule*.{out_format}')) + \
                list(cwd.glob(f'packages_fleet_manager_on_mule*.{out_format}'))
    
    if not generated:
        print(f"No {out_format.upper()} files generated by pyreverse.")
        sys.exit(4)
    
    for f in generated:
        target = out_dir / f.name
        try:
            f.replace(target)
            size_kb = target.stat().st_size / 1024
            print(f"✓ Saved: {target} ({size_kb:.1f} KB)")
        except Exception as e:
            print(f"Failed to move {f}: {e}")
    
    print('Done')


if __name__ == '__main__':
    main()
