set -e 
source /app/scripts/pull_from_master_fm.sh

MASTER_FM_IP=$1
MASTER_FM_PORT=$2
HTTP_SCHEME=$3
FM_VERSION=$4
prod=$5
MASTER_FM_REGISTRY_USERNAME=$6
MASTER_FM_REGISTRY_PASSWORD=$7
STATIC_FILE_AUTH_USERNAME=$8
STATIC_FILE_AUTH_PASSWORD=$9


download_pull_fm_update $MASTER_FM_IP $MASTER_FM_PORT $HTTP_SCHEME $FM_VERSION $prod $MASTER_FM_REGISTRY_USERNAME $MASTER_FM_REGISTRY_PASSWORD $STATIC_FILE_AUTH_USERNAME $STATIC_FILE_AUTH_PASSWORD


